### ISSUE TITLE
Rolled back to an earlier hash, but no update detected

### ISSUE THREAD

**Issue by jbuberel** [divan/gofresh#1]
Decided to test gofresh on a small test app (github.com/jbuberel/prime_finder).

Created a new dir, set the GOPATH:

```
> go get github.com/jbuberel/prime_finder
> cd src/github.com/jbuberel/prime_finder
> git reset --hard 9694c6e27eb1a5125e53f2541b08004f9a94c967
HEAD is now at 9694c6e Remove line
> gofresh
Found 0 imports, checking for updates...
Everything is up to date.
```

Expected to be told that my prime_finder package needed to be updated. What am I doing wrong with my workflow here?

**Comment by divan** [comment]
Oh, I probably must write usage more clear.

If you don't specify package(s) name, gofresh searches for packages that are imported in your current package. In your case there is no package in prime_finder at all (you have packages in subdirs), so it tells 'Found 0 imports'.

But, if you do specify package name explicitly:

```
gofresh github.com/jbuberel/prime_finder
```

then you will get desired behaviour - it will tell you about new commits:

```
$ gofresh github.com/jbuberel/prime_finder
Checking 1 packages for updates...
github.com/jbuberel/prime_finder [✅ 3]
    574ccde working redis configuratin
    674a9e8 Adding redis support
    1c8e8e2 Adding redis test
---
You have 1 packages out of date
To update all packages automatically, run gofresh -update
```

To be clear, the basic usage is 'tell me what packages need to be upgraded for my current project'.

**Comment by jbuberel** [comment]
The confusing part is the terminology you're using - `current project` - as Go has no formal definition of a current project. There just all source files under your $GOPATH.

Can you define that more explicitly?

PS If you help me define it, I'll help update your readme ;-)

**Comment by divan** [comment]
Yes, 'current project' is the package found in the current directory with it's subpackages :)

**Comment by jbuberel** [comment]
I understand now - so for the `gofresh` command to work without specifying a package, it must be executed in a directory that contains a .go source file. Is that correct?

**Comment by divan** [comment]
Correct. And thanks for updating README.
