### ISSUE TITLE
Recursive check?

### ISSUE THREAD

**Issue by ghost** [divan/gofresh#11]
Is it possible to check recursive libraries within folder?

Its just too slow to go from directory to directory

**Comment by divan** [comment]
Hi. Nope, there is no such feature, but it can easily be achieved with sh commands, like _find_.

```
for i in $(find $GOPATH/src/github.com/divan -depth 1 -type d); do
     cd $i && gofresh
done
```

**Comment by ghost** [comment]
Thanks
