### ISSUE TITLE
Similar project, can I add a link to it?

### ISSUE THREAD

**Issue by dmitshur** [divan/gofresh#12]
Hi there @divan,

If I'm not mistaken, this project looks quite similar to [Go Package Store](https://github.com/shurcooL/Go-Package-Store#readme). They both are meant to help view updates to Go packages and update them. One obvious difference I see is that GoFresh runs in a terminal, while Go Package Store uses a browser to display its output.

I think [it's a good idea](https://github.com/shurcooL/vfsgen/pull/6#issue-107431054) to link to similar projects (it helps the users) in READMEs, so I'd like to add a link to GoFresh in a new "Alternatives" section of README of Go Package Store (for an example of such section, see https://github.com/shurcooL/vfsgen#alternatives).

Is that okay with you?

**Comment by divan** [comment]
Hi! Yep, totally. Nice idea!
https://github.com/divan/gofresh/commit/3f516b194b3df7027f6296451a18b00e31f89f9b

**Comment by dmitshur** [comment]
Great, thank you! :)

I've added GoFresh to my README in https://github.com/shurcooL/Go-Package-Store/commit/f4374965c96944d352314602299835adabaf366f.
