### ISSUE TITLE
exit status 128?

### ISSUE THREAD

**Issue by porjo** [divan/gofresh#4]
```
$ gofresh golang.org/x/crypto/bcrypt
Checking 1 packages for updates...
golang.org/x/crypto/bcrypt: exit status 128
Everything is up to date.

$ gofresh golang.org/x/exp/utf8string
Checking 1 packages for updates...
golang.org/x/exp/utf8string: exit status 128
Everything is up to date.
```

The local copies of these packages are actually not up to date.

**Comment by divan** [comment]
Yeah, it's mentioned in Readme#Issues - failed repos or errors aren't reported.

Can you please go manually to yours $GOPATH/src/golang.org/x/crypto/bcrypt and run

```
git log HEAD..origin/master --oneline
```

You probably will have an error message there from git.

I'm planning to add error reporting for git/cmd related errors, anyway.

**Comment by porjo** [comment]
bcrypt is a sub-package of `crypto`, so has not VCS repo itself. `crypto` is a Mercurial repo. So the issue appears to be handling sub-packages from non-Git repos.

**Comment by divan** [comment]
Now I see. golang.org repos moved to github since 1.4. At least my copy of $GOPATH/src/golang.org/x/crypto is under git.

Anyway, command for getting commits for Mercurial is `hg incoming -n -q --template "{node|short} {desc|strip|firstline}"`. What's the output, when invoked from bcrypt/ dir?

**Comment by porjo** [comment]
`hg incoming -n -q --template "{node|short} {desc|strip|firstline}"` produces no output when invoked from bcrypt dir

Yes, I think my paths were a bit screwed. I've blown away $GOPATH/src/golang.org/x and re-pulled what I need and `gofresh` is happy now. Thanks!
